### ISSUE TITLE
Week 3 Review Ticket

### ISSUE THREAD

**Issue by Archkitten** [nolanplatt/AP-CSA-Tri2#2]
Design Manager (Akshay):
- [ ] Bootstrap Layouts
- [ ] 3 Frontend Screens with design/functionality towards Project Theme
- [ ] Unit 2 and Unit 3 FRQ online [INDIVIDUAL]

Scrum Master (Arch):
- [ ] GitHub README, Tickets, Wiki
- [ ] Week 4 Backlog
- [ ] Unit 2 and Unit 3 FRQ online [INDIVIDUAL]

Technical Officer (Dane):
- [ ] Access data Async + Database with CRUD (Create Read Update Delete) operations
- [ ] Unit 2 and Unit 3 FRQ online [INDIVIDUAL]

Deployment Manager (Nolan):
- [ ] Website running from https (Certbot)
- [ ] Process to perform update ready to demonstrate
- [ ] Unit 2 and Unit 3 FRQ online [INDIVIDUAL]

GitHub Admin (Chris):
- [ ] Highlight commits and pull requests from each individual
- [ ] Unit 2 and Unit 3 FRQ online [INDIVIDUAL]

**Comment by nolanplatt** [comment]
**Nolan Platt - Individual Grade**
- [x] [Website running from https (Certbot)](https://github.com/nolanplatt/AP-CSA-T2/commit/4df3e5b06972d4ed4cb4e3a2eaa9c37988adf92b)
- [x] [Process to perform update ready to demonstrate](https://nighthawkrecruiting.tk)
- [x] [Unit 2 FRQ online [INDIVIDUAL]](https://github.com/nolanplatt/AP-CSA-T2/commit/4df3e5b06972d4ed4cb4e3a2eaa9c37988adf92b)
- [x] [Unit 3 FRQ online [INDIVIDUAL]](https://github.com/nolanplatt/AP-CSA-T2/commit/2054e304f72b6f6a3cb887e335820afc0e9f896a)

**Grade: 8/8**
- I completed all assignments in a timely fashion, and provided different approaches to the unit two and unit three FRQs. I incorporated this into classes on the Java backend combined with an API in order to get the code to the frontend display on my individual about page.

**Comment by Chris-Ru** [comment]
Chris Rubin 
5 of 5 team,
2 of 2 [frq2 + frq3 link(s)](https://nighthawkrecruiting.tk/individual/CRubin#FRQ):  7/7

**Comment by Chris-Ru** [comment]
> **Nolan Platt - Individual Grade**
> 
> * [x]  [Website running from https (Certbot)](https://github.com/nolanplatt/AP-CSA-T2/commit/4df3e5b06972d4ed4cb4e3a2eaa9c37988adf92b)
> * [x]  [Process to perform update ready to demonstrate](https://nighthawkrecruiting.tk)
> * [x]  [Unit 2 FRQ online [INDIVIDUAL]](https://github.com/nolanplatt/AP-CSA-T2/commit/4df3e5b06972d4ed4cb4e3a2eaa9c37988adf92b)
> * [x]  [Unit 3 FRQ online [INDIVIDUAL]](https://github.com/nolanplatt/AP-CSA-T2/commit/2054e304f72b6f6a3cb887e335820afc0e9f896a)
> 
> **Grade: 8/8**
> 
> * I completed all assignments in a timely fashion, and provided different approaches to the unit two and unit three FRQs. I incorporated this into classes on the Java backend combined with an API in order to get the code to the frontend display on my individual about page.

Has demonstrated quick action on deployment. Took over deployment manager well by getting project running with https by Wednesday.

**Comment by nolanplatt** [comment]
> **Chris Rubin - Individual Grade**
> 
> * [x]  [Highlight commits and pull requests from each individual](https://github.com/nolanplatt/AP-CSA-T2#the-team)
> 
> **Grade: 7/7**
> 
> * 5 of 5 team
> * 2 of 2 [frq2 + frq3 link(s)](https://nighthawkrecruiting.tk/individual/CRubin#FRQ) and [ticket w/ instructions on formatting](https://github.com/nolanplatt/AP-CSA-T2/projects/1#card-74849446)_(ctrl+shift+left click to open properly)_:  7/7

I agree with Chris's individual review. He deserves 8/8 for his great teamwork and individual commits as Github Admin. Has organized GitHub well and coordinated with Scrum Master and rest of team good as well.

**Comment by Akshay-Rohatgi** [comment]
**Nolan Platt - Individual Grade**

_Links to Individual FRQ Runtime Links_
- [Unit 2 FRQ online](https://nighthawkrecruiting.tk/individual/ARohatgi#unit2FRQ)
- [Unit 3 FRQ online](https://nighthawkrecruiting.tk/individual/ARohatgi#unit3FRQ)

**Tasks List**
- [x] [3 pages and base CSS created for website](https://github.com/nolanplatt/AP-CSA-T2/commit/c35ec4ae4813e39c75f51b2ca5413c3616686be3)
- [x] [Unit 2 and 3 FRQ online [INDIVIDUAL]](https://github.com/nolanplatt/AP-CSA-T2/commit/73b2395efdb952206ff8bfbcf0c0ee9c81f13e6d)

**Grade: 8/8**
- All individual assignments were completed on time and began and implemented website design for the team. 3 pages were completed and more are currently being built. Will communicate frontend requirements to the rest of the team so that everyone is on the same page when adding new pages and features.

**Comment by Akshay-Rohatgi** [comment]
> **Nolan Platt - Individual Grade**
> 
> _Links to Individual FRQ Runtime Links_
> 
> * [Unit 2 FRQ online](https://nighthawkrecruiting.tk/individual/NPlatt#unit2FRQ)
> * [Unit 3 FRQ online](https://nighthawkrecruiting.tk/individual/NPlatt#unit3FRQ)
> * [2014 FRQ Extra Credit](https://nighthawkrecruiting.tk/individual/NPlatt#extraCreditFRQ) +2 extra credit
> 
> **Tasks List**
> 
> * [x]  [Website running from https (Certbot)](https://github.com/nolanplatt/AP-CSA-T2/commit/4df3e5b06972d4ed4cb4e3a2eaa9c37988adf92b)
> * [x]  [Process to perform update ready to demonstrate](https://nighthawkrecruiting.tk)
> * [x]  [Unit 2 FRQ online [INDIVIDUAL]](https://github.com/nolanplatt/AP-CSA-T2/commit/4df3e5b06972d4ed4cb4e3a2eaa9c37988adf92b)
> * [x]  [Unit 3 FRQ online [INDIVIDUAL]](https://github.com/nolanplatt/AP-CSA-T2/commit/2054e304f72b6f6a3cb887e335820afc0e9f896a)
> * [x]  [2014 FRQ Extra Credit [INDIVIDUAL]](https://docs.google.com/document/d/1t9ekir1K0GmBIL0SIBatH0Q-bg6ndCrwc-QSujz6K84/edit?usp=sharing) +2 extra credit
> 
> **Grade: 10/8**
> 
> * I completed all assignments in a timely fashion, and provided different approaches to the unit two and unit three FRQs. I incorporated this into classes on the Java backend combined with an API in order to get the code to the frontend display on my individual about page.

Extremely valuable contributions to the team, deployment was working soon after the new team was organized. Managed runtime for FRQs for everyone's about pages.

**Comment by Akshay-Rohatgi** [comment]
> > **Nolan Platt - Individual Grade**
> > 
> > * [x]   [Website running from https (Certbot)](https://github.com/nolanplatt/AP-CSA-T2/commit/4df3e5b06972d4ed4cb4e3a2eaa9c37988adf92b)
> > * [x]   [Process to perform update ready to demonstrate](https://nighthawkrecruiting.tk)
> > * [x]   [Unit 2 FRQ online [INDIVIDUAL]](https://github.com/nolanplatt/AP-CSA-T2/commit/4df3e5b06972d4ed4cb4e3a2eaa9c37988adf92b)
> > * [x]   [Unit 3 FRQ online [INDIVIDUAL]](https://github.com/nolanplatt/AP-CSA-T2/commit/2054e304f72b6f6a3cb887e335820afc0e9f896a)
> > 
> > **Grade: 8/8**
> > 
> > * I completed all assignments in a timely fashion, and provided different approaches to the unit two and unit three FRQs. I incorporated this into classes on the Java backend combined with an API in order to get the code to the frontend display on my individual about page.
> 
> Has demonstrated quick action on deployment. Took over deployment manager well by getting project running with https by Wednesday.

Great organization of repository and coordination with all members of the team while managing the most important tool of our project, Github.

**Comment by Akshay-Rohatgi** [comment]
> **Chris Rubin - Individual Grade**
> 
> * [x]  [Highlight commits and pull requests from each individual](https://github.com/nolanplatt/AP-CSA-T2#the-team)
> 
> **Grade: 7/7**
> 
> * 5 of 5 team
> * 2 of 2 [frq2 + frq3 link(s)](https://nighthawkrecruiting.tk/individual/CRubin#FRQ) and [ticket w/ instructions on formatting](https://github.com/nolanplatt/AP-CSA-T2/projects/1#card-74849446)_(ctrl+shift+left click to open properly)_:  7/7

Great coordination with all parts of team and was instrumental in managing the most important tool for our project, Github.

**Comment by nolanplatt** [comment]
> **Akshay Rohatgi - Individual Grade**
> 
> _Links to Individual FRQ Runtime Links_
> 
> * [Unit 2 FRQ online](https://nighthawkrecruiting.tk/individual/ARohatgi#unit2FRQ)
> * [Unit 3 FRQ online](https://nighthawkrecruiting.tk/individual/ARohatgi#unit3FRQ)
> 
> **Tasks List**
> 
> * [x]  [3 pages and base CSS created for website](https://github.com/nolanplatt/AP-CSA-T2/commit/c35ec4ae4813e39c75f51b2ca5413c3616686be3)
> * [x]  [Unit 2 and 3 FRQ online [INDIVIDUAL]](https://github.com/nolanplatt/AP-CSA-T2/commit/73b2395efdb952206ff8bfbcf0c0ee9c81f13e6d)
> 
> **Grade: 8/8**
> 
> * All individual assignments were completed on time and began and implemented website design for the team. 3 pages were completed and more are currently being built. Will communicate frontend requirements to the rest of the team so that everyone is on the same page when adding new pages and features.

I agree with Akshay's individual grade. He designed the wireframe well along with all of his tasks for week three. He was also able to quickly implement these designs into our website. Great job overall, 8/8.

**Comment by jm1021** [comment]
Chris R, Akshay, Nolan 6.75/7.   -.5 for no integration of FRQ classes with clear input between front end and back end.  +.25 back for collaboration and commenting on this page.

Arch, Dane 5/7
